"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%^@5%ui$7qda5r*^u_@++r=@zfmjtw(f0)5n+)2tii+m+d!046'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ==============================================================================
# REAL-WORLD ANALOGY: Registering a New Shop in a Shopping Mall
# ------------------------------------------------------------------------------
# Imagine you just built a physical storefront inside a giant shopping mall.
# The mall has security, electricity, and water systems (Django's built-in apps).
# Even though your shop's building is fully constructed and the sign is up,
# customers cannot visit and the mall directory will not list you until you
# officially register your shop with the mall's head office.
# 
# Adding 'gallery' to the INSTALLED_APPS array is exactly like submitting your registration
# form to Django's head office. It officially tells the main Django engine:
# "Hey, please activate and load our newly built 'gallery' app so it can connect
# to the database, use templates, and handle image uploads in our portfolio system!"
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Registering our accounts app to manage user authentication (register, login, logout)
    'accounts',
    # Registering our gallery app to manage albums, photos, and file uploads
    'gallery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ==============================================================================
# REAL-WORLD ANALOGY: Updating the Security Guard's Manual
# ------------------------------------------------------------------------------
# Imagine the Django settings file is the master blueprint and manual for your entire
# web application's building. By default, the blueprint tells the building's
# security guard (Django's auth engine) to use the standard factory-issue keys
# (the default auth.User model) to unlock doors.
# 
# Now that we have crafted custom keys (our new User model inside the 'accounts' app),
# the security guard will completely ignore them and still ask for the factory-issue keys
# unless we explicitly update the security manual.
# 
# Adding AUTH_USER_MODEL is like crossing out the old instructions in the security manual
# and writing in bold letters: "ATTENTION: From now on, use the custom 'accounts.User' 
# model as the official key card template for everyone in the building!"
# ==============================================================================

# We tell Django to use our custom User model instead of the default built-in User model.
# The format is 'app_name.ModelName', which in our case is 'accounts.User'.
# This must be defined before running migrations for the first time, otherwise
# Django will set up database tables using the old default model and cause major conflicts later.
AUTH_USER_MODEL = 'accounts.User'

# ==============================================================================
# REAL-WORLD ANALOGY: The Bouncer's Redirection Instructions
# ------------------------------------------------------------------------------
# Imagine you try to walk straight past the bouncer into the club's VIP Private Lounge
# (the protected Dashboard) without a valid visitor session pass.
# 
# The bouncer stops you. But instead of just throwing you into the street and locking the
# door (which would leave the visitor confused!), the bouncer needs to know where to direct you.
# 
# Defining LOGIN_URL is like giving the bouncer a clear instruction manual:
# "When you kick an unauthenticated visitor out of a protected room, politely walk them
# over to the Login registration gate (our view path named 'login') so they can sign in!"
# ==============================================================================

# We tell Django where to redirect unauthenticated users when they try to access a protected view.
# By passing the URL name 'login', Django will look up the path mapped to name='login' in our URLs.
LOGIN_URL = 'login'

# ==============================================================================
# REAL-WORLD ANALOGY: The Public Shop Display vs the Physical Storage Warehouse
# ------------------------------------------------------------------------------
# Imagine you are running a premium photography framing business.
# 
# 1. The Physical Warehouse (MEDIA_ROOT):
# This is a large, secure physical building (a folder on your hard drive) where all
# the heavy raw canvases, printed photographs, and picture frames are actually stored.
# If a photo file is uploaded by a customer, this is the exact hard drive folder on the
# computer where the file gets saved.
# 
# 2. The Public Display Window (MEDIA_URL):
# You don't want customers walking into your dusty warehouse and searching through shelves!
# Instead, you build a sleek glass display window on the street side with a clear sign
# labeled "/media/". When a client wants to see their picture, they don't look in the warehouse;
# they just walk up to the street address and look through the display window at "/media/my-photo.jpg".
# 
# MEDIA_URL tells the web browser what public address prefix to use when requesting an image.
# MEDIA_ROOT tells the server's filesystem exactly where to write and save that file.
# ==============================================================================

# The public web address path prefix that Django will prepend to the URL of any uploaded file.
# For example, an image named 'sunset.jpg' will be requested by the browser at '/media/sunset.jpg'.
# This must start and end with a forward slash to form a valid address path prefix.
MEDIA_URL = '/media/'

# The absolute filesystem path to the directory on your computer's hard drive where uploaded media files will be saved.
# We use BASE_DIR (which represents the project's root folder) and join it with a folder named 'media'.
# Django will automatically create this directory if it doesn't already exist when a file is saved.
MEDIA_ROOT = BASE_DIR / 'media'

